AUTHSYS/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('app1/',include('app1.urls',namespace='app1'))
]

app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [ 
    path('signup',views.signup,name='signup'),
    path('login',views.userlogin,name='login'),
    path('logout',views.userlogout,name='logout'),
    path('profile',views.Profile,name='profile'),
    path('changepassword',views.changepassword,name='changepassword'),
    path('changepassword2',views.changepassword2,name='changepassword2'),
]

app1/models.py
from django.db import models

# Create your models here.

app1/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django import forms


class SignupForm(UserCreationForm):
    password2 = forms.CharField(label='RE-ENTER PASSWORD',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']


class UpdateuserprofileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','date_joined','last_login','is_active']


class UpdateadminprofileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields ='__all__'

app1/views.py
from django.shortcuts import render,HttpResponseRedirect
from app1.forms import SignupForm,UpdateuserprofileForm,UpdateadminprofileForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm,SetPasswordForm
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash
from django.contrib.auth.models import User


# Create your views here.

def index(request):
    return render(request,'app1/index.html',{'msg':'This is Index Page'})

def signup(request):
    if request.method == 'POST':
        form =SignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'REGISTERED SUCCESSFULLY')
    else:
        form = SignupForm()
    return render(request,'app1/signup.html',{'form':form})

def userlogin(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request,data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username,password=password)
                if user is not None:
                    login(request,user)
                    messages.success(request,'LOGGED IN SUCCESSFULLY')
                    return HttpResponseRedirect('/app1/profile')
        else:
            form = AuthenticationForm()
        return render(request,'app1/login.html',{'form':form})    
    else:
        return HttpResponseRedirect('/app1/profile')
    

def userlogout(request):
    logout(request)
    return HttpResponseRedirect('/app1/login')

def Profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            users=None
            form = UpdateuserprofileForm(request.POST,instance=request.user)
            if form.is_valid():
                form.save()
                messages.success(request,'PROFILE UPDATED SUCCESSFULLY')
        else:
            if request.user.is_superuser == True:
                form = UpdateadminprofileForm(instance=request.POST)
                users = User.objects.all()
            else:
                form = UpdateuserprofileForm(instance=request.user)
                users =None
        context = {'msg':'WELCOME TO YOUR PROFILE','user':request.user,'form':form,'users':users} 
        return render(request,'app1/profile.html',context) 
    else:
        return HttpResponseRedirect('/app1/login')    

def changepassword(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(user=request.user,data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request,form.user)
                messages.success(request,'YOUR PASSWORD HASS BEEN CHANGED')
                return HttpResponseRedirect('/app1/login')
        else:
            form=PasswordChangeForm(user=request.user)
        return render(request,'app1/cp.html',{'form':form})
    else:
        return HttpResponseRedirect('/app1/login')

            
def changepassword2(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = SetPasswordForm(user=request.user,data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request,form.user)
                messages.success(request,'YOUR PASSWORD HASS BEEN CHANGED')
                return HttpResponseRedirect('/app1/profile')
        else:
            form=SetPasswordForm(user=request.user)
        return render(request,'app1/cp.html',{'form':form})
    else:
        return HttpResponseRedirect('/app1/login')

            

templates/app1/cp.html
{% extends 'base.html' %}
{% block b1 %}
    <div class="container">
        <div class="text-left">
            <a href="{% url 'app1:profile' %}">BACK</a>
        </div>
    </div>
    <h3 style="color: midnightblue;" >{{msg}} {{user}}</h3>
    <form action="" method="post">
        {% csrf_token %}
        {% for i in form %}
            <label class="col-sm-1" for="">{{i.label_tag}}</label>  
            {{i}}{{i.errors|striptags}} <br> <br>
        {% endfor %}
        <input type="submit" value="SUBMIT">
    </form>
    <div class="text-center text-success" >
        {% if messages %}
            {% for i in messages %}
                {{i}}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/app1/index.html
{% extends 'base.html' %}
{% block b1 %}  
<div>
    <a class="btn btn-info" href="{% url 'app1:signup' %}">SIGNUP</a>
    <a class="btn btn-info" href="{% url 'app1:login' %}">LOGIN</a>
</div>
    <h2>{{msg}}</h2>
{% endblock  %}

templates/app1/login.html
{% extends 'base.html' %}
{% block b1 %} 
    <form action="" method="post">
        <div class="form-group row">
                {% csrf_token %}
                {% for i in form %}
                    <label class="col-sm-2 offset-sm-4 col-form-label" for="">{{i.label_tag}}</label>
                    <div class="col-sm-3">{{i}}{{i.errors|striptags}}</div>
                {% endfor %}  
        </div>
        <input class="btn btn-success col-sm-1 offset-sm-1" type="submit" value="LOGIN">
    </form>
    <div class="text-center text-success" >
        {% if messages %}
            {% for i in messages %}
                {{i}}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/app1/profile.html
{% extends 'base.html' %}
{% block b1 %}
    <div class="container">
        <div style="text-align: left;" >
            <a class="btn btn-info" href="{% url 'app1:logout' %}">LOGOUT</a> 
            <a class="btn btn-info" href="{% url 'app1:changepassword' %}">CHANGEPASSWORD</a>
            <a class="btn btn-info" href="{% url 'app1:changepassword2' %}">RESET PASSWORD</a>
        </div>
    </div>
    <h3 style="color: midnightblue;" >{{msg}} {{user}}</h3>
    <form action="" method="post">
        {% csrf_token %}
        {% for i in form %}
            <label class="col-sm-1" for="">{{i.label_tag}}</label>  
            {{i}}{{i.errors|striptags}} <br> <br>
        {% endfor %}
        <input type="submit" value="UPDATE">
    </form>
    <div class="text-center text-success" >
        {% if messages %}
            {% for i in messages %}
                {{i}}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/app1/signup.html
{% extends 'base.html' %}
{% block b1 %} 
    <form action="" method="post">
        <div class="form-group row">
                {% csrf_token %}
                {% for i in form %}
                    <label class="col-sm-2 offset-sm-4 col-form-label" for="">{{i.label_tag}}</label>
                    <div class="col-sm-3">{{i}}{{i.errors|striptags}}</div>
                {% endfor %}  
        </div>
        <input class="btn btn-primary col-sm-1 offset-sm-1" type="submit" value="SIGNUP">
        <a class="btn btn-info" href="{% url 'app1:login' %}">LOGIN</a>
    </form>
    <div class="text-center text-success">
        {% if messages %}
            {% for i in messages %}
                {{i}}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    <div class="container">
        <div class="sticky-top">
            <h1 class="text-center p-3 mb-2 bg-info text-dark">Django Web Development : AUTHENSYS</h1>
        </div>
        <div class="c1 text-center">
            {% block b1 %}
            {% endblock %}
        </div>
        <div class="container fixed-bottom">
            <h1 class="text-center p-3 mb-2 bg-info text-dark">Thanks for visiting</h1>
        </div>
    </div>
</body>
</html>